### ISSUE TITLE
healthchecks 监控检查需要自己实现吗

### ISSUE THREAD

**Issue by nodyang** [xljiulang/AspnetcoreKong#1]

**Comment by nodyang** [comment]
![image](https://user-images.githubusercontent.com/3090191/81049889-aaadc980-8ef1-11ea-866a-7e06a514fc9f.png)
我用demo 跑的。一直这个错误

**Comment by nodyang** [comment]
![image](https://user-images.githubusercontent.com/3090191/81051416-3a547780-8ef4-11ea-96fa-fe69db07bae5.png)
![image](https://user-images.githubusercontent.com/3090191/81051455-46403980-8ef4-11ea-9f22-6a742ea3d448.png)
我就简单的实现了一个。似乎不工作。求指点

**Comment by xljiulang** [comment]
使用endpoints.MapHealthChecks()扩展方法即可

**Comment by nodyang** [comment]
> 使用endpoints.MapHealthChecks()扩展方法即可
是我们局域网的问题。项目已经上线。谢谢
