### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by nodyang** [xljiulang/AspnetcoreKong#3]
1 我的api采用docker 部署  我用asp.net kong 获取本地的IP是docker 的地址  似乎注册后 访问不了
只能手动的去注入宿主的IP  有没有好的方案去解决这个问题。

**Comment by xljiulang** [comment]
在docker把kong与其它服务加入同一个网络即可

**Comment by nodyang** [comment]
我服务docker 和kong 是2个服务器 。是不是不好搞
